language: node_js
node_js:
- node
#services: mongodb
cache:
  directories:
  - node_modules
  yarn: true
before_install:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then echo "this is a pull request build";
  fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then echo "this is not not not a pull requets
  build"; fi
- openssl aes-256-cbc -K $encrypted_476ad15a8e52_key -iv $encrypted_476ad15a8e52_iv -in super_secret.txt.enc -out super_secret.txt -d
- chmod 600 ~/.ssh/id_rsa
- mv -fv .travis/ssh-config ~/.ssh/config
- git config --global user.name "BarrelRider65"
- git config --global user.email "862785121@qq.com"
- chmod +x .travis/deploy.sh
script:
- sh ./travis/deploy.sh


